### PR TITLE
restyling 2024

### PR DESCRIPTION
**Pull request by a-gave**
This introduces a new theme similar to material for mkdocs
This also follows the discussion of the last few meetings at https://lists.autistici.org/message/20240107.174212.f777433f.en.html

The preview of the site is visible at: 
[https://libremesh.antennine.campiinrete.org/](https://libremesh.antennine.campiinrete.org/)

Since the last preview, I made these changes, reviewed also by @digitigrafo:
- some cleaning to the previous code, fixed some UI stuffs and updated jekyll to 4.33, 
- introduced a page for the `lime-example` and for each lime-packages, to have them also on the website (this shows at least the `Makefile` - that often contains a meaningful *description* -  and if available it includes also the `Readme.md`)

Currently, and as before, only pages that are directly contained in the `/docs/` folder (depth: 1) are copied to firmware images for offline documentation (when selecting the package `lime-docs` during building)

New pages should be added manually in the file `_data/structure.yml` to be visible also in the left menu.
I hope that this theme and the ability to expand menu items, may lead to an expansion of the documentation and an increased clarity, while keeping a concise approach possible to avoid unnecessarily burdening the firmware images.

### CODE REVIEW

**Comment by ilario** [comment]
Awesome!!!!!

The documentation from the packages is a greeeat new feature!!
And it pushes us to do some cleaning in the packages, in order to keep that list reasonably useful... There are packages that nobody uses since years, likely. We should make a list and ask in the mailing list.
This is the reference issue for this:
https://github.com/libremesh/lime-packages/issues/977

In the title you wrote that this is a draft. Can we merge or should we wait?

**Comment by a-gave** [comment]
> This is the reference issue for this:
https://github.com/libremesh/lime-packages/issues/977

Thanks for this! I will look at it again

I did these changes:
- enabled **full-text search** (the default one broke with punctuation marks)
- add a way **to prefetch all packages** readme and makefiles using a script (because the plugin `jekyll_github_sample` does not work well if the files are many - I left it only for the lime-example file)
- **improved the table of content** (the default one was buggy and didn't highlight the chapter you are reading)

It is now 99% mergeable, I'll give it one last review soon and then ping

**Comment by digitigrafo** [comment]
This is a big improvement for the usability of our website! thanks -agave

**Comment by ilario** [comment]
Beautiful, thanks!!!!

**Pull request merged**
